# Generated by Django 4.2.2 on 2023-06-23 15:16

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_order_receipt_alter_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(null=True, upload_to=shopapp.models.product_preview_dir_path),
        ),
    ]
