# Generated by Django 4.2.2 on 2023-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_productimage'),
        ('shopapp', '0013_productimage'),
    ]

    operations = [
    ]
